name: GitHub Pages

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Build site
        env:
          GITALK_CLIENT_ID: ${{ secrets.GITALK_CLIENT_ID }}
          GITALK_CLIENT_SECRET: ${{ secrets.GITALK_CLIENT_SECRET }}
        run: |
          echo "gitalk:" >> _config.yml
          echo "  clientID: '${GITALK_CLIENT_ID}'" >> _config.yml
          echo "  clientSecret: '${GITALK_CLIENT_SECRET}'" >> _config.yml
          echo "  repo: 'moselikk.github.io'" >> _config.yml
          echo "  owner: 'moselikk'" >> _config.yml
          echo "  admin: ['moselikk']" >> _config.yml
          echo "  distractionFreeMode: false" >> _config.yml
          bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site