name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v1

      - name: Build with Jekyll
        run: |
          echo "gitalk:" >> _config.yml
          echo "  clientID: '${{ secrets.GITALK_CLIENT_ID }}'" >> _config.yml
          echo "  clientSecret: '${{ secrets.GITALK_CLIENT_SECRET }}'" >> _config.yml
          echo "  repo: 'moselikk/moselikk.github.io'" >> _config.yml
          echo "  owner: 'moselikk'" >> _config.yml
          echo "  admin: ['moselikk']" >> _config.yml
          echo "  distractionFreeMode: false" >> _config.yml
          bundle exec jekyll build --destination _site --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: jekyll-build
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository-name: ${{ github.repository }}
          branch: gh-pages
          folder: _site