name: Build and Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 新增：安装 yq (YAML 处理工具)
      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install yq

      # 安全修改 _config.yml
      - name: Configure Gitalk
        run: |
          yq eval '
            .gitalk.clientID = strenv(GITALK_CLIENT_ID) |
            .gitalk.clientSecret = strenv(GITALK_CLIENT_SECRET) |
            .gitalk.repo = strenv(GITALK_REPO) |
            .gitalk.owner = strenv(GITALK_OWNER) |
            .gitalk.admin = [strenv(GITALK_OWNER)] |
            .gitalk.distractionFreeMode = false
          ' -i _config.yml
        env:
          GITALK_CLIENT_ID: ${{ secrets.GITALK_CLIENT_ID }}
          GITALK_CLIENT_SECRET: ${{ secrets.GITALK_CLIENT_SECRET }}
          GITALK_REPO: ${{ github.repository }}
          GITALK_OWNER: ${{ github.repository_owner }}

      # 缓存优化版（增加 yq 缓存）
      - uses: actions/cache@v4
        with:
          path: |
            ~/snap
            .asdf/**
            vendor/bundle
          key: ${{ runner.os }}-cache-${{ hashFiles('**/cache.key') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      # 完整部署配置
      - uses: jeffreytse/jekyll-deploy-action@v0.6.0
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'gh-pages'
          jekyll_src: './'
          jekyll_cfg: '_config.yml'
          ruby_ver: '3.2.0'  # 明确指定 Ruby 版本
          bundler_ver: '2.5.0'
          pre_build_commands: |
            sudo apt-get update
            sudo apt-get install -y libvips libvips-dev  # 常见图片处理依赖